theme: minima
title: Data Science
author: LockhartTech
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Buckle up!. This site is about Data Science, Artificial Intelligence, and Machine Learning.

# social links
twitter_username: LockhartTech # DO NOT include the @ character, or else the build will fail!
github_username:  LockhartTech # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
